runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: false
    APP_ENV: production
    APP_KEY: base64:PSQdzd3BFnwjAmyiNcywL51Y/2AtBliBoLz3LxJ783o=
    APP_NAME: "RC Dwella"

    LOG_LEVEL: debug

    MIDTRANS_BOOK_PREFIX: "BOOK-TRX-0"
    MIDTRANS_TRANSACTION_PREFIX: "TRX-0"

    MIDTRANS_CLIENT_KEY: "Mid-client-QiT9F9tQUS-pbbNt" 
    MIDTRANS_SERVER_KEY: "Mid-server-e2keiEdZwZWRBODWUO4Dcvp0" 
    MIDTRANS_IS_PRODUCTION: false
    MIDTRANS_IS_SANITIZED: true
    MIDTRANS_IS_3DS: true

    SHIPPING_COST: 11000